// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/audit-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit-log">> = Specific
  const handler = {} as typeof import("../../src/app/admin/audit-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/features">> = Specific
  const handler = {} as typeof import("../../src/app/admin/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/profiles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/profiles">> = Specific
  const handler = {} as typeof import("../../src/app/admin/profiles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assets">> = Specific
  const handler = {} as typeof import("../../src/app/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/audit-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-log">> = Specific
  const handler = {} as typeof import("../../src/app/audit-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auto-link/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auto-link">> = Specific
  const handler = {} as typeof import("../../src/app/auto-link/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bank-accounts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank-accounts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/bank-accounts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bank-accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank-accounts">> = Specific
  const handler = {} as typeof import("../../src/app/bank-accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/budgets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/budgets">> = Specific
  const handler = {} as typeof import("../../src/app/budgets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/deals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deals">> = Specific
  const handler = {} as typeof import("../../src/app/deals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/expenses/archive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses/archive">> = Specific
  const handler = {} as typeof import("../../src/app/expenses/archive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/expenses/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses/import">> = Specific
  const handler = {} as typeof import("../../src/app/expenses/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses">> = Specific
  const handler = {} as typeof import("../../src/app/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/expenses/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses/vendors">> = Specific
  const handler = {} as typeof import("../../src/app/expenses/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/family/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/family">> = Specific
  const handler = {} as typeof import("../../src/app/family/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gmail-import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gmail-import">> = Specific
  const handler = {} as typeof import("../../src/app/gmail-import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/goals">> = Specific
  const handler = {} as typeof import("../../src/app/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide">> = Specific
  const handler = {} as typeof import("../../src/app/guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/health">> = Specific
  const handler = {} as typeof import("../../src/app/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/income/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/income">> = Specific
  const handler = {} as typeof import("../../src/app/income/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/insights">> = Specific
  const handler = {} as typeof import("../../src/app/insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/insurance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/insurance">> = Specific
  const handler = {} as typeof import("../../src/app/insurance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/investments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investments">> = Specific
  const handler = {} as typeof import("../../src/app/investments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/loans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/loans">> = Specific
  const handler = {} as typeof import("../../src/app/loans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/net-worth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/net-worth">> = Specific
  const handler = {} as typeof import("../../src/app/net-worth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plans">> = Specific
  const handler = {} as typeof import("../../src/app/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reminders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reminders">> = Specific
  const handler = {} as typeof import("../../src/app/reminders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/risk-profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/risk-profile">> = Specific
  const handler = {} as typeof import("../../src/app/risk-profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/settings/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/bank-accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/bank-accounts">> = Specific
  const handler = {} as typeof import("../../src/app/settings/bank-accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/database/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/database">> = Specific
  const handler = {} as typeof import("../../src/app/settings/database/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/environment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/environment">> = Specific
  const handler = {} as typeof import("../../src/app/settings/environment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/gmail-parser/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/gmail-parser">> = Specific
  const handler = {} as typeof import("../../src/app/settings/gmail-parser/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/settings/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/session-link/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/session-link">> = Specific
  const handler = {} as typeof import("../../src/app/settings/session-link/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/setup-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup-guide">> = Specific
  const handler = {} as typeof import("../../src/app/setup-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup">> = Specific
  const handler = {} as typeof import("../../src/app/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tax/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tax">> = Specific
  const handler = {} as typeof import("../../src/app/tax/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/what-if/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/what-if">> = Specific
  const handler = {} as typeof import("../../src/app/what-if/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/audit-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit-log">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/audit-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/db-mode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/db-mode">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/db-mode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/features/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/features/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/features/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/features/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/features">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/features/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/features/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/features/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/features/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/profiles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/profiles/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/profiles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/profiles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/profiles">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/profiles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/tier/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tier">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/tier/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/audit-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit-log">> = Specific
  const handler = {} as typeof import("../../src/app/api/audit-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/google/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/google">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/google/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/mobile-google/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/mobile-google/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/mobile-google/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/mobile-google/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/mobile-google">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/mobile-google/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/mobile-google/success/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/mobile-google/success">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/mobile-google/success/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/mobile-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/mobile-login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/mobile-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/test-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/test-login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/test-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auto-link/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auto-link/accept">> = Specific
  const handler = {} as typeof import("../../src/app/api/auto-link/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auto-link/suggestions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auto-link/suggestions">> = Specific
  const handler = {} as typeof import("../../src/app/api/auto-link/suggestions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bank-accounts/[id]/fds/[fdId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bank-accounts/[id]/fds/[fdId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/bank-accounts/[id]/fds/[fdId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bank-accounts/[id]/fds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bank-accounts/[id]/fds">> = Specific
  const handler = {} as typeof import("../../src/app/api/bank-accounts/[id]/fds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bank-accounts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bank-accounts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/bank-accounts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bank-accounts/[id]/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bank-accounts/[id]/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/bank-accounts/[id]/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bank-accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bank-accounts">> = Specific
  const handler = {} as typeof import("../../src/app/api/bank-accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bank-accounts/sync-balances/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bank-accounts/sync-balances">> = Specific
  const handler = {} as typeof import("../../src/app/api/bank-accounts/sync-balances/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bank-analysis/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bank-analysis/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/bank-analysis/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/budgets/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/budgets/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/budgets/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/budgets/repeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/budgets/repeat">> = Specific
  const handler = {} as typeof import("../../src/app/api/budgets/repeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/budgets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/budgets">> = Specific
  const handler = {} as typeof import("../../src/app/api/budgets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cash-balance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cash-balance">> = Specific
  const handler = {} as typeof import("../../src/app/api/cash-balance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/categories">> = Specific
  const handler = {} as typeof import("../../src/app/api/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/deals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deals">> = Specific
  const handler = {} as typeof import("../../src/app/api/deals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/discover-gpay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discover-gpay">> = Specific
  const handler = {} as typeof import("../../src/app/api/discover-gpay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drive/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drive/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/drive/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drive/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drive/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/drive/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drive/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drive/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/drive/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/archive">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/batch-delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/batch-delete">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/batch-delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/bulk-delete-range/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/bulk-delete-range">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/bulk-delete-range/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/flagged/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/flagged">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/flagged/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/years/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/years">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/years/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/my-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/my-data">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/my-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/family/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/family/accept">> = Specific
  const handler = {} as typeof import("../../src/app/api/family/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/family/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/family/invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/family/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/family/members/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/family/members/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/family/members/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/family/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/family/members">> = Specific
  const handler = {} as typeof import("../../src/app/api/family/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/family/revoke/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/family/revoke">> = Specific
  const handler = {} as typeof import("../../src/app/api/family/revoke/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/files/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/files/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/files/receipt/[name]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/receipt/[name]">> = Specific
  const handler = {} as typeof import("../../src/app/api/files/receipt/[name]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gap-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gap-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/api/gap-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gmail/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gmail/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/gmail/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gmail/keywords/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gmail/keywords">> = Specific
  const handler = {} as typeof import("../../src/app/api/gmail/keywords/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gmail/scan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gmail/scan">> = Specific
  const handler = {} as typeof import("../../src/app/api/gmail/scan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gmail/scan/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gmail/scan/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/gmail/scan/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/goals/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/goals/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/goals/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/goals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/goals">> = Specific
  const handler = {} as typeof import("../../src/app/api/goals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health-report/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health-report/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/health-report/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health-score/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health-score">> = Specific
  const handler = {} as typeof import("../../src/app/api/health-score/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/import-sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import-sessions">> = Specific
  const handler = {} as typeof import("../../src/app/api/import-sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/import/bank-analysis/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/bank-analysis/apply">> = Specific
  const handler = {} as typeof import("../../src/app/api/import/bank-analysis/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/import/bank-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/bank-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/api/import/bank-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/import/bank-csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/bank-csv">> = Specific
  const handler = {} as typeof import("../../src/app/api/import/bank-csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/import/bank-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/bank-pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/import/bank-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/import/gpay-preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/gpay-preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/import/gpay-preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/import/kcexpenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/kcexpenses">> = Specific
  const handler = {} as typeof import("../../src/app/api/import/kcexpenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/import/mappings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/mappings">> = Specific
  const handler = {} as typeof import("../../src/app/api/import/mappings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/import/restore-duplicates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/restore-duplicates">> = Specific
  const handler = {} as typeof import("../../src/app/api/import/restore-duplicates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/income/sources/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/income/sources/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/income/sources/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/income/sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/income/sources">> = Specific
  const handler = {} as typeof import("../../src/app/api/income/sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/income/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/income/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/income/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/insights/deep/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insights/deep">> = Specific
  const handler = {} as typeof import("../../src/app/api/insights/deep/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/insights/domains/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insights/domains">> = Specific
  const handler = {} as typeof import("../../src/app/api/insights/domains/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/insights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insights">> = Specific
  const handler = {} as typeof import("../../src/app/api/insights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/insights/yoy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insights/yoy">> = Specific
  const handler = {} as typeof import("../../src/app/api/insights/yoy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/insurance/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insurance/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/insurance/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/insurance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insurance">> = Specific
  const handler = {} as typeof import("../../src/app/api/insurance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/groww/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/groww">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/groww/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/mf-central/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/mf-central">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/mf-central/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/sharekhan/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/sharekhan/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/sharekhan/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/sharekhan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/sharekhan">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/sharekhan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/zerodha/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/zerodha/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/zerodha/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/zerodha/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/zerodha">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/zerodha/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/investments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investments">> = Specific
  const handler = {} as typeof import("../../src/app/api/investments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/liabilities/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/liabilities/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/liabilities/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/liabilities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/liabilities">> = Specific
  const handler = {} as typeof import("../../src/app/api/liabilities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/loans/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/loans/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/loans/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/loans/amortization/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/loans/amortization">> = Specific
  const handler = {} as typeof import("../../src/app/api/loans/amortization/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/loans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/loans">> = Specific
  const handler = {} as typeof import("../../src/app/api/loans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/net-worth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/net-worth">> = Specific
  const handler = {} as typeof import("../../src/app/api/net-worth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/onboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/api/onboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/onboarding/welcome/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/welcome">> = Specific
  const handler = {} as typeof import("../../src/app/api/onboarding/welcome/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/create-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/create-order">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/create-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/mobile-checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/mobile-checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/mobile-checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rates/epf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rates/epf">> = Specific
  const handler = {} as typeof import("../../src/app/api/rates/epf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/receipt/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/receipt/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/receipt/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommendations">> = Specific
  const handler = {} as typeof import("../../src/app/api/recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/refresh-gpay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/refresh-gpay">> = Specific
  const handler = {} as typeof import("../../src/app/api/refresh-gpay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/refresh-gpay/status/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/refresh-gpay/status/[jobId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/refresh-gpay/status/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reminders/auto-detect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reminders/auto-detect">> = Specific
  const handler = {} as typeof import("../../src/app/api/reminders/auto-detect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reminders">> = Specific
  const handler = {} as typeof import("../../src/app/api/reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/recurrence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/recurrence">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/recurrence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/risk-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/risk-profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/risk-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/environment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/environment">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/environment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/gmail-parser/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/gmail-parser">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/gmail-parser/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/setup/admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup/admin">> = Specific
  const handler = {} as typeof import("../../src/app/api/setup/admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/setup/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/setup/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tax/documents/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tax/documents/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tax/documents/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tax/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tax/documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/tax/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tax/itr/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tax/itr/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tax/itr/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tax/itr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tax/itr">> = Specific
  const handler = {} as typeof import("../../src/app/api/tax/itr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tax/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tax/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/tax/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/preferences">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/push-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/push-token">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/push-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vendors/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendors/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/vendors/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vendors/all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendors/all">> = Specific
  const handler = {} as typeof import("../../src/app/api/vendors/all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vendors/apply-mappings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendors/apply-mappings">> = Specific
  const handler = {} as typeof import("../../src/app/api/vendors/apply-mappings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vendors/batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendors/batch">> = Specific
  const handler = {} as typeof import("../../src/app/api/vendors/batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vendors/bulk-delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendors/bulk-delete">> = Specific
  const handler = {} as typeof import("../../src/app/api/vendors/bulk-delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vendors/latest-timestamp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendors/latest-timestamp">> = Specific
  const handler = {} as typeof import("../../src/app/api/vendors/latest-timestamp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vendors/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendors/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/vendors/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vendors/unmapped/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendors/unmapped">> = Specific
  const handler = {} as typeof import("../../src/app/api/vendors/unmapped/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/razorpay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/razorpay">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/razorpay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/what-if/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/what-if">> = Specific
  const handler = {} as typeof import("../../src/app/api/what-if/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
