// ── Generate Version Info ───────────────────────────────────────────────
// Run automatically before `next build`. Produces NEXT_PUBLIC_COMMIT_COUNT,
// NEXT_PUBLIC_COMMIT_SHA, and NEXT_PUBLIC_BUILD_TIME. These are picked up
// at build time and embedded into the client bundle (because of the
// NEXT_PUBLIC_ prefix).
//
// Usage:  tsx scripts/version-info.ts
// The numbers are written to .env.version (auto-loaded by Next.js) so they
// become available during `next build`.

import { execSync } from "node:child_process"
import { writeFileSync, existsSync } from "node:fs"
import { join } from "node:path"

function safeExec(cmd: string): string {
  try {
    return execSync(cmd, { encoding: "utf8" }).trim()
  } catch {
    return ""
  }
}

function main() {
  const cwd = process.cwd()
  const envFile = join(cwd, ".env.version")

  let commitCount = "0"
  let commitSha = "dev"
  let branch = "unknown"
  let buildTime = ""

  if (existsSync(join(cwd, ".git"))) {
    commitCount = safeExec("git rev-list --count HEAD") || "0"
    commitSha = safeExec("git rev-parse HEAD") || "dev"
    branch = safeExec("git rev-parse --abbrev-ref HEAD") || "unknown"
  }

  buildTime = new Date().toISOString()

  // Format: KEY=value
  // NEXT_PUBLIC_ prefix exposes them to the client bundle.
  const lines = [
    `# Auto-generated by scripts/version-info.ts — DO NOT EDIT`,
    `# Generated at: ${buildTime}`,
    `NEXT_PUBLIC_COMMIT_COUNT=${commitCount}`,
    `NEXT_PUBLIC_COMMIT_SHA=${commitSha}`,
    `NEXT_PUBLIC_BUILD_TIME=${buildTime}`,
    `NEXT_PUBLIC_BUILD_BRANCH=${branch}`,
  ]

  writeFileSync(envFile, lines.join("\n") + "\n", "utf8")
  console.log(`[version-info] build: ${commitCount} | sha: ${commitSha.slice(0, 7)} | branch: ${branch}`)
}

main()
