export interface ControlItem {
  name: string
  description: string
  location?: string
}

export interface WorkflowStep {
  step: string
  description: string
  example?: string
}

export interface HelpSection {
  title: string
  summary: string
  details: string
  controls?: ControlItem[]
  workflow?: WorkflowStep[]
  relatedFeatures?: { name: string; description: string }[]
}

const helpContent: Record<string, HelpSection> = {
  "/": {
    title: "Dashboard",
    summary: "Your home screen — see how your money is doing at a glance.",
    details: "The Dashboard pulls data from every part of the app to give you a quick snapshot: your total income, expenses this month, investments, active goals, and a Financial Health Score. The charts show how your income and expenses trend over time. Tap any stat card to jump to that section.",
    controls: [
      { name: "Month/Year Selector", description: "Dropdowns at the top to choose which month and year to view.", location: "Top bar" },
      { name: "Stat Cards", description: "Tappable cards showing Annual Income, Total Expenses, This Month's Spend, Investments, Active Goals.", location: "Main grid" },
      { name: "Financial Health Gauge", description: "Circular gauge showing your 0–100 health score.", location: "Below stat cards" },
      { name: "Income vs Expenses Chart", description: "Line chart comparing income and expenses over the selected period.", location: "Middle section" },
      { name: "Spending Breakdown Chart", description: "Pie or bar chart showing category-wise spending.", location: "Below trend chart" },
    ],
    workflow: [
      { step: "Check your numbers", description: "Stat cards show annual income, total expenses, this month's spend, investments, and goals." },
      { step: "Adjust the time period", description: "Use the month/year selector to view historical data.", example: "Select 'March 2026' to see that month's stats." },
      { step: "See your financial health", description: "The gauge rates you from 0–100. Below 50 means room to improve." },
      { step: "Spot trends", description: "Charts show income vs expenses over time and where your money goes." },
      { step: "Take action", description: "Tap any stat card to go straight to that section.", example: "Tap the Expenses card to open the full expense list." },
    ],
    relatedFeatures: [
      { name: "Income Sources", description: "The income stat comes from all your income sources." },
      { name: "Expenses", description: "The expense stat comes from your recorded expenses." },
      { name: "Financial Health", description: "The gauge on the Dashboard takes you to your full health report." },
    ],
  },
  "/expenses": {
    title: "All Expenses",
    summary: "Every expense, all in one place — add, edit, filter, and find anything fast.",
    details: "Your complete transaction log. Each expense records the date, amount, category, description, payment method, and payee. Filter by category, vendor, person, or amount range. Use the search bar to find specific entries. Swipe or tap the edit icon to modify a row. Data flows into Budgets, Auto-Link, Reports, and Tax.",
    controls: [
      { name: "Add Expense Button", description: "Floating action button to create a new expense entry.", location: "Bottom right" },
      { name: "Search Bar", description: "Text input to search expenses by description or vendor.", location: "Top" },
      { name: "Filter Buttons", description: "Chip-style filters for category, payment method, date range.", location: "Below search bar" },
      { name: "Sort Toggle", description: "Dropdown to sort by date, amount, or category asc/desc.", location: "Top right" },
      { name: "Edit Icon", description: "Pencil icon on each row to open the edit form.", location: "Per row" },
      { name: "Delete Action", description: "Trash icon with confirmation dialog to remove an expense.", location: "Per row" },
      { name: "Import Button", description: "Navigates to the bulk import screen.", location: "Top bar or header menu" },
    ],
    workflow: [
      { step: "Add an expense", description: "Tap the Add button. Fill in date, amount, category, payment method, and payee.", example: "Tap + → select 'Food' → enter ₹450 → pick 'UPI' → tap Save." },
      { step: "Find past expenses", description: "Use filter buttons to narrow down by category, vendor, or amount.", example: "Tap 'Transport' filter to see all travel-related spending." },
      { step: "Search for a specific entry", description: "Type a keyword in the search bar to filter results.", example: "Search 'Amazon' to find all Amazon purchases." },
      { step: "Edit or delete", description: "Tap the pencil icon to edit. Use delete with confirmation.", example: "Tap the pencil → change ₹500 to ₹450 → tap Save." },
    ],
    relatedFeatures: [
      { name: "Budgets", description: "Your spending adds up against the budgets you've set." },
      { name: "Auto-Link", description: "Expenses marked 'Investment' can become investment records." },
      { name: "Reports", description: "See your spending breakdown in Reports." },
      { name: "Bulk Import", description: "Add multiple expenses at once by uploading a file." },
    ],
  },
  "/expenses/import": {
    title: "Bulk Import",
    summary: "Add lots of expenses at once by uploading a bank statement, CSV, or GPay export.",
    details: "Upload your bank statement (CSV or PDF), an Excel file, or a Google Takeout export. The app reads the data, you map the columns to the correct fields, and everything gets added at once. Duplicate detection stops you from importing the same transaction twice. Review the preview before confirming.",
    controls: [
      { name: "Upload Button", description: "File picker to select CSV, XLSX, or PDF files from your device.", location: "Upload area" },
      { name: "Column Mapping Dropdowns", description: "Map each file column to app fields (date, amount, description).", location: "After file upload" },
      { name: "Preview Table", description: "Scrollable table showing how rows will look after mapping.", location: "Below column mapping" },
      { name: "Import Button", description: "Confirm and execute the import of all previewed rows.", location: "Bottom" },
      { name: "Duplicate Warning", description: "Highlighted rows that match existing expenses.", location: "Preview table" },
    ],
    workflow: [
      { step: "Upload your file", description: "Tap the upload area and select a CSV, XLSX, or PDF file from your phone.", example: "Select a February bank statement CSV from your Downloads folder." },
      { step: "Map the columns", description: "For each column in your file, select what field it represents.", example: "Map 'Date' → date, 'Amount' → amount, 'Description' → description." },
      { step: "Review the preview", description: "Check the preview table to make sure everything looks correct before importing." },
      { step: "Handle duplicates", description: "If duplicates are detected, review and skip them or import all." },
      { step: "Confirm import", description: "Tap the Import button. New expenses appear in the main list." },
    ],
    relatedFeatures: [
      { name: "Expenses", description: "Imported expenses appear in the main list." },
      { name: "Merchants", description: "Vendor names can be mapped to known merchants for cleaner data." },
    ],
  },
  "/expenses/archive": {
    title: "Archive",
    summary: "Hide old or test entries without permanently deleting them.",
    details: "Archiving soft-deletes an expense — hidden from your main list but still in the database. Use this to clean up your main view without losing data. You can restore archived entries back to the main list or permanently delete them from this screen.",
    controls: [
      { name: "Restore Button", description: "Undo icon to move an expense back to the main list.", location: "Per row" },
      { name: "Permanent Delete", description: "Trash icon with confirmation to permanently remove an expense.", location: "Per row" },
      { name: "Select All", description: "Checkbox to select all archived items for batch actions.", location: "Top bar" },
      { name: "Batch Restore", description: "Restore all selected items at once.", location: "Top bar" },
      { name: "Batch Delete", description: "Permanently delete all selected items with confirmation.", location: "Top bar" },
    ],
    workflow: [
      { step: "View archived entries", description: "The screen lists all soft-deleted expenses with original details." },
      { step: "Restore an entry", description: "Tap Restore to move an expense back to the main list.", example: "Tap Restore on a test expense you now want to keep." },
      { step: "Permanently delete", description: "Tap Delete and confirm to erase the expense forever.", example: "Delete old entries from 2023 that are no longer needed." },
      { step: "Batch actions", description: "Use Select All then choose Restore or Delete to handle multiple items at once." },
    ],
    relatedFeatures: [
      { name: "Expenses", description: "Archived entries can be restored to the main view." },
    ],
  },
  "/expenses/vendors": {
    title: "Vendors",
    summary: "Standardise vendor names so 'Starbucks' always looks the same.",
    details: "Merchant mapping lets you set a standard name and category for each vendor. When you import or add new expenses with matching vendor names, the app automatically uses the standard name and category. This keeps your data clean and your reports accurate.",
    controls: [
      { name: "Add Mapping Button", description: "Opens a form to create a new merchant mapping.", location: "Top bar" },
      { name: "Standard Name Input", description: "The canonical name you want all variations to map to.", location: "Mapping form" },
      { name: "Alias Input", description: "Alternative spellings or names that should map to the standard name.", location: "Mapping form" },
      { name: "Category Selector", description: "Assign a default category for expenses from this merchant.", location: "Mapping form" },
      { name: "Edit Mapping", description: "Tap an existing mapping to change its name, aliases, or category.", location: "Per row" },
      { name: "Delete Mapping", description: "Remove a mapping with confirmation.", location: "Per row" },
      { name: "Search Mappings", description: "Filter the list by merchant name or alias.", location: "Top" },
    ],
    workflow: [
      { step: "Add a new mapping", description: "Tap Add Mapping. Enter the standard name, any aliases, and a default category.", example: "Standard name: 'Starbucks', aliases: 'Starbucks India', 'SBUX', category: 'Food & Drink'." },
      { step: "Edit an existing mapping", description: "Tap any row to update the name, aliases, or category.", example: "Add 'McD' as an alias for 'McDonald's'." },
      { step: "Search mappings", description: "Use the search bar to find a specific merchant quickly." },
    ],
    relatedFeatures: [
      { name: "Expenses", description: "Merchant mappings auto-categorise expenses during import." },
      { name: "Reports", description: "Clean vendor data means more accurate category reports." },
      { name: "Bulk Import", description: "Mappings are especially useful after importing new data." },
    ],
  },
  "/income": {
    title: "Income Sources",
    summary: "Keep track of every rupee you earn — salary, rent, interest, business, or anything else.",
    details: "List all the ways money comes in. Each income source can be monthly, yearly, one-time, or variable. For business income, you can track revenue, expenses, and profit separately. Your total income feeds into the Dashboard, Budgets, Reports, Tax calculations, and Net Worth.",
    controls: [
      { name: "Add Source Button", description: "Opens the form to add a new income source.", location: "Top bar" },
      { name: "Income Type Selector", description: "Choose from Salary, Business, Rental, Interest, Freelance, Other.", location: "Add/Edit form" },
      { name: "Amount Input", description: "Numeric field for the income amount.", location: "Add/Edit form" },
      { name: "Frequency Selector", description: "Monthly, Yearly, One-Time, or Variable.", location: "Add/Edit form" },
      { name: "Category Selector", description: "Assign a category for reporting purposes.", location: "Add/Edit form" },
      { name: "Business Revenue/Expense Fields", description: "Separate fields for revenue and expenses when type is Business.", location: "Add/Edit form" },
      { name: "Filter/Search", description: "Filter by type, frequency, or search by name.", location: "Top" },
      { name: "Edit/Delete", description: "Tap a row to edit; swipe or use the menu to delete.", location: "Per row" },
      { name: "Summary Cards", description: "Cards showing monthly, yearly, and this-month totals.", location: "Top section" },
    ],
    workflow: [
      { step: "Add a new income source", description: "Tap Add Source. Pick a type, enter the amount, choose frequency and category.", example: "Type: Salary, Amount: ₹75,000, Frequency: Monthly, Category: Primary Income." },
      { step: "Track business income", description: "For Business type, enter your revenue and expenses. Profit is calculated automatically.", example: "Revenue: ₹2,00,000, Expenses: ₹1,20,000 → Profit: ₹80,000." },
      { step: "See the totals", description: "The summary cards show your monthly, yearly, and this-month income.", example: "Total Monthly Income: ₹1,25,000." },
      { step: "Edit or remove", description: "Tap any source to edit its details. Delete removes it from all calculations." },
    ],
    relatedFeatures: [
      { name: "Expenses", description: "Income minus Expenses equals your savings rate." },
      { name: "Budgets", description: "Each budget shows what percentage of your income it represents." },
      { name: "Tax", description: "Income sources add up to your Gross Total Income." },
      { name: "Net Worth", description: "Income increases your net worth over time." },
    ],
  },
  "/budgets": {
    title: "Budgets",
    summary: "Set spending limits for each category and see how you're tracking.",
    details: "Budgets help you plan how much to spend on each category every month. Set a limit for Food, Transport, Shopping, or anything else. The page shows what percentage of your total income each budget represents, how much you've spent, and what's left. Colour warnings tell you when you're getting close to your limit.",
    controls: [
      { name: "Add Budget Button", description: "Opens the form to create a new budget.", location: "Top bar" },
      { name: "Category Selector", description: "Pick the expense category this budget applies to.", location: "Add/Edit form" },
      { name: "Limit Input", description: "Set the monthly spending limit for this category.", location: "Add/Edit form" },
      { name: "Month Selector", description: "Choose which month and year this budget is for.", location: "Add/Edit form" },
      { name: "Progress Bar", description: "Visual bar showing spent vs limit with colour coding.", location: "Per budget card" },
      { name: "Percentage of Income", description: "Text showing what % of income this budget consumes.", location: "Per budget card" },
      { name: "Active/Inactive Filter", description: "Toggle to show only active or all budgets.", location: "Top" },
      { name: "Edit/Delete", description: "Tap to edit the limit or category; delete removes the budget.", location: "Per row" },
    ],
    workflow: [
      { step: "Create a budget", description: "Tap Add Budget. Pick a category, set your monthly limit, and choose the month.", example: "Category: Food, Limit: ₹10,000, Month: April 2026." },
      { step: "Track your spending", description: "The progress bar shows spent vs limit. Green = under, Yellow = close, Red = over.", example: "Spent ₹7,500 of ₹10,000 → bar is yellow at 75%." },
      { step: "See it as % of income", description: "Each budget shows what % of your monthly income it uses.", example: "₹10,000 of ₹1,00,000 = 10% of your income." },
      { step: "Adjust or remove", description: "Tap a budget to edit its limit. Delete if you no longer need it." },
    ],
    relatedFeatures: [
      { name: "Income Sources", description: "Your total income is used to calculate budget percentages." },
      { name: "Expenses", description: "Your actual spending is compared against budgets automatically." },
    ],
  },
  "/investments": {
    title: "Investments",
    summary: "Track your portfolio — stocks, mutual funds, FD, PPF, NPS, gold, and more.",
    details: "Manage everything you've invested in. Different types have their own fields. Returns (XIRR) are calculated and compared to benchmarks. Link investments to Goals, import from brokers, or export your portfolio. Investment data feeds into Net Worth and Tax.",
    controls: [
      { name: "Add Investment Button", description: "Opens the form to add a new investment.", location: "Top bar" },
      { name: "Type Selector", description: "Choose from Stocks, Mutual Funds, FD, PPF, NPS, Gold, Real Estate, Crypto.", location: "Add form" },
      { name: "Amount/Units Input", description: "Enter the amount invested or number of units purchased.", location: "Add form" },
      { name: "Date Picker", description: "Select the purchase or investment date.", location: "Add form" },
      { name: "Goal Link Selector", description: "Connect this investment to an existing goal.", location: "Add form" },
      { name: "Broker Import Button", description: "Import holdings directly from your broker.", location: "Top bar" },
      { name: "Export Button", description: "Export your portfolio to Excel or PDF.", location: "Top bar" },
      { name: "XIRR Display", description: "Shows your extended internal rate of return vs benchmarks.", location: "Per investment card" },
      { name: "Edit/Delete", description: "Tap to edit details; swipe or menu to delete.", location: "Per row" },
    ],
    workflow: [
      { step: "Add an investment", description: "Tap Add Investment. Choose the type, enter the amount/units and purchase date.", example: "Type: Mutual Fund, Fund: HDFC Mid-Cap, Amount: ₹50,000, Date: 01-Jan-2026." },
      { step: "Link to a goal", description: "Connect this investment to a goal — progress updates automatically.", example: "Link this fund to the 'Buy a Car' goal." },
      { step: "Check your returns", description: "View your XIRR and compare it against benchmarks.", example: "XIRR: 14.2% vs NIFTY 50: 12.1%." },
      { step: "Import from broker", description: "Tap Import Broker Data and provide your broker credentials or upload a statement." },
      { step: "Export portfolio", description: "Use the Export button to download your holdings as a report." },
    ],
    relatedFeatures: [
      { name: "Goals", description: "Investments can be linked to track goal progress." },
      { name: "Net Worth", description: "Your investments are part of your net worth calculation." },
      { name: "Tax", description: "Capital gains from investments are used in tax calculations." },
      { name: "Auto-Link", description: "Investment-related expenses can auto-create investment records." },
    ],
  },
  "/goals": {
    title: "Goals",
    summary: "Set financial goals — a new car, a house, retirement — and track progress.",
    details: "Goals help you plan for the future. Each goal has a target amount, a deadline, a term, and a priority. You can link investments to goals — as investments grow, your goal progress updates automatically. Goals also appear on the Dashboard as a stat card.",
    controls: [
      { name: "Add Goal Button", description: "Opens the form to create a new goal.", location: "Top bar" },
      { name: "Name Input", description: "Give your goal a descriptive name.", location: "Add form" },
      { name: "Target Amount Input", description: "Set the total amount you need to achieve.", location: "Add form" },
      { name: "Deadline Date Picker", description: "Select the target date for achieving this goal.", location: "Add form" },
      { name: "Priority Selector", description: "Low, Medium, or High priority.", location: "Add form" },
      { name: "Progress Bar", description: "Visual indicator showing saved vs target.", location: "Per goal card" },
      { name: "Link Investments", description: "Connect existing investments to this goal.", location: "Per goal detail" },
      { name: "Edit/Delete", description: "Tap to edit; delete removes the goal and optional investment links.", location: "Per row" },
    ],
    workflow: [
      { step: "Create a goal", description: "Tap Add Goal. Give it a name, target amount, deadline, and priority.", example: "Name: 'Buy a Car', Target: ₹10,00,000, Deadline: Dec 2027, Priority: High." },
      { step: "Track progress", description: "Update your contribution amount. The progress bar shows how close you are.", example: "You've saved ₹3,50,000 of ₹10,00,000 (35%)." },
      { step: "Link investments", description: "Connect investments to this goal — they'll track progress together.", example: "Link your mutual fund SIP to the 'Buy a Car' goal." },
      { step: "Adjust as needed", description: "Edit the target or deadline if your plans change." },
    ],
    relatedFeatures: [
      { name: "Investments", description: "Link investments to track goal progress automatically." },
      { name: "Dashboard", description: "Active goals appear as a stat card on your home screen." },
      { name: "What-If Simulator", description: "Model how increased savings accelerate goal achievement." },
    ],
  },
  "/bank-accounts": {
    title: "Bank Accounts",
    summary: "Link your bank accounts to track balances and see everything in one place.",
    details: "Add your savings, current, and other bank accounts with account number, IFSC, bank name, branch, and current balance. Account balances feed into your Net Worth. Income sources and expenses can reference specific accounts for better tracking.",
    controls: [
      { name: "Add Account Button", description: "Opens the form to add a new bank account.", location: "Top bar" },
      { name: "Bank Name Input", description: "Name of the bank.", location: "Add form" },
      { name: "Account Number Input", description: "Your account number (masked for display).", location: "Add form" },
      { name: "IFSC Code Input", description: "IFSC code for the branch.", location: "Add form" },
      { name: "Branch Input", description: "Branch name or location.", location: "Add form" },
      { name: "Balance Input", description: "Current balance of the account.", location: "Add form" },
      { name: "Account Type Selector", description: "Savings, Current, Salary, NRI, etc.", location: "Add form" },
      { name: "Quick Balance Update", description: "Inline edit to update the balance without opening the full form.", location: "Per card" },
      { name: "Edit/Delete", description: "Tap any account to edit; delete removes it from net worth.", location: "Per row" },
    ],
    workflow: [
      { step: "Add an account", description: "Tap Add Account. Enter the bank name, account number, IFSC, and current balance.", example: "HDFC Bank, account ending 1234, IFSC: HDFC0001234, Balance: ₹50,000." },
      { step: "Keep balances updated", description: "Update balances periodically to keep your Net Worth accurate.", example: "End of month: update your savings balance." },
      { step: "Link to income/expenses", description: "When adding income or expenses, select the account for better tracking." },
    ],
    relatedFeatures: [
      { name: "Net Worth", description: "Account balances contribute to your net worth." },
      { name: "Income Sources", description: "Income can be linked to a specific bank account." },
      { name: "Bank Account Detail", description: "Tap an account to see its transaction history." },
    ],
  },
  "/bank-accounts/[id]": {
    title: "Bank Account Detail",
    summary: "See everything about one bank account — balance, quick stats, and linked transactions.",
    details: "This detail view shows a single account's balance, account info, and all income/expenses linked to it. You can edit the account details, update the balance, or delete the account. Quick stats show total credits and debits linked to this account.",
    controls: [
      { name: "Account Info Card", description: "Shows bank name, account number (masked), IFSC, branch, and type.", location: "Top" },
      { name: "Balance Display", description: "Large text showing the current balance.", location: "Top" },
      { name: "Quick Stats", description: "Total credits and debits linked to this account.", location: "Below balance" },
      { name: "Transaction List", description: "Scrollable list of all income and expenses linked to this account.", location: "Main area" },
      { name: "Edit Account", description: "Opens the edit form to modify account details.", location: "Top bar" },
      { name: "Update Balance", description: "Inline or form input to update the current balance.", location: "Top bar or balance area" },
      { name: "Delete Account", description: "Permanently removes the account with confirmation.", location: "Menu or settings" },
    ],
    workflow: [
      { step: "View account details", description: "The top card shows all stored information about the account.", example: "HDFC Savings, Balance: ₹50,000, IFSC: HDFC0001234." },
      { step: "See linked transactions", description: "Scroll through all income and expenses that reference this account." },
      { step: "Update the balance", description: "Tap the balance area to enter a new current balance.", example: "Update from ₹50,000 to ₹52,300 after a deposit." },
      { step: "Edit or delete", description: "Use the edit button to update account info. Delete removes the account from all calculations." },
    ],
    relatedFeatures: [
      { name: "Bank Accounts", description: "All accounts are listed in the main bank accounts page." },
      { name: "Net Worth", description: "This account's balance contributes to total net worth." },
      { name: "Expenses", description: "Expenses paid from this account appear in the transaction list." },
    ],
  },
  "/net-worth": {
    title: "Net Worth",
    summary: "What you own minus what you owe — the single most important number in your finances.",
    details: "Net Worth is everything you own (assets + investments + insurance value + business profit) minus everything you owe (loan balances). The page shows what you own vs what you owe with a visual breakdown. Tap any entry to go to its full module. Tracking Net Worth over time shows if you're building wealth.",
    controls: [
      { name: "Net Worth Number", description: "Large display showing Total Assets minus Total Liabilities.", location: "Top" },
      { name: "Assets vs Liabilities Chart", description: "Bar or pie chart comparing what you own vs what you owe.", location: "Below net worth" },
      { name: "Breakdown List", description: "Each asset, investment, account, and loan listed with its value.", location: "Main area" },
      { name: "Time Range Selector", description: "Switch between Current, Monthly, or Yearly view.", location: "Top bar" },
      { name: "Net Worth Trend Chart", description: "Line chart showing how net worth has changed over time.", location: "Middle" },
      { name: "Tap to Navigate", description: "Tap any item in the breakdown to open its detail page.", location: "Per row" },
    ],
    workflow: [
      { step: "See your number", description: "Total Assets minus Total Liabilities = Your Net Worth.", example: "₹85,00,000 − ₹25,00,000 = ₹60,00,000 Net Worth." },
      { step: "Review the breakdown", description: "See each component — investments, assets, bank balances, loans." },
      { step: "Track over time", description: "Use the trend chart to see if your net worth is growing.", example: "Net Worth grew from ₹55L to ₹60L this quarter." },
      { step: "Dig deeper", description: "Tap any item to go to its full module for details.", example: "Tap a loan entry to see repayment details." },
    ],
    relatedFeatures: [
      { name: "Assets", description: "Physical assets add to what you own." },
      { name: "Investments", description: "Financial investments add to what you own." },
      { name: "Loans", description: "Loan balances are what you owe." },
      { name: "Bank Accounts", description: "Account balances contribute to assets." },
    ],
  },
  "/subscriptions": {
    title: "Subscriptions",
    summary: "Track all your recurring payments — Netflix, Prime, gym, apps — and never miss a renewal.",
    details: "Subscriptions tracks everything you pay for regularly. Each entry has the service name, provider, amount, billing cycle, next due date, and status. The app calculates your total monthly and yearly subscription spend. Upcoming renewals appear in Reminders automatically.",
    controls: [
      { name: "Add Subscription Button", description: "Opens the form to add a new subscription.", location: "Top bar" },
      { name: "Service Name Input", description: "Name of the subscription service.", location: "Add form" },
      { name: "Provider Input", description: "The company providing the service.", location: "Add form" },
      { name: "Amount Input", description: "How much you pay per billing cycle.", location: "Add form" },
      { name: "Billing Cycle Selector", description: "Monthly, Quarterly, Half-Yearly, Yearly.", location: "Add form" },
      { name: "Next Due Date Picker", description: "When the next payment is due.", location: "Add form" },
      { name: "Status Selector", description: "Active, Paused, or Cancelled.", location: "Add form" },
      { name: "Monthly/Yearly Total Cards", description: "Aggregated spend on all active subscriptions.", location: "Top" },
      { name: "Filter by Status", description: "Show Active, Paused, or Cancelled subscriptions.", location: "Top" },
      { name: "Edit/Delete", description: "Tap to edit; delete removes the subscription.", location: "Per row" },
    ],
    workflow: [
      { step: "Add a subscription", description: "Tap Add Subscription. Enter name, provider, amount, billing cycle, and next renewal.", example: "Netflix, Provider: Netflix Inc., ₹649/month, next due: 15-Aug-2026." },
      { step: "See what you're spending", description: "The page shows monthly and yearly totals for all active subscriptions.", example: "Total: ₹3,200/month, ₹38,400/year." },
      { step: "Pause or cancel", description: "Change the status to paused or cancelled as needed.", example: "Pause your gym subscription during a vacation." },
      { step: "Never miss a payment", description: "Renewal reminders are auto-created in the Reminders module." },
    ],
    relatedFeatures: [
      { name: "Reminders", description: "Subscription renewals appear as reminders automatically." },
      { name: "Expenses", description: "Subscription payments can also be recorded as expenses." },
    ],
  },
  "/insurance": {
    title: "Insurance",
    summary: "Manage your policies — health, life, vehicle — so you never miss a renewal.",
    details: "Insurance keeps all your policies in one place. Each record stores the type, provider, policy number, sum assured, premium, renewal date, and nominee. Renewal reminders appear in Reminders automatically. Premiums paid are tracked for tax deduction purposes under Section 80C and 80D.",
    controls: [
      { name: "Add Policy Button", description: "Opens the form to add a new insurance policy.", location: "Top bar" },
      { name: "Type Selector", description: "Health, Life, Term, Vehicle, Travel, Property.", location: "Add form" },
      { name: "Provider Input", description: "Insurance company name.", location: "Add form" },
      { name: "Policy Number Input", description: "Your unique policy number.", location: "Add form" },
      { name: "Sum Assured Input", description: "Total coverage amount.", location: "Add form" },
      { name: "Premium Input", description: "Amount paid per cycle.", location: "Add form" },
      { name: "Renewal Date Picker", description: "Next renewal or expiry date.", location: "Add form" },
      { name: "Nominee Input", description: "Name of the nominee.", location: "Add form" },
      { name: "Filter by Type", description: "Show only Health, Life, etc.", location: "Top" },
      { name: "Edit/Delete", description: "Tap to edit; delete removes the policy.", location: "Per row" },
    ],
    workflow: [
      { step: "Add a policy", description: "Tap Add Insurance. Pick the type, enter provider, policy number, sum assured, and premium.", example: "Health: HDFC Ergo, Policy: HDFC-12345, Sum: ₹5,00,000, Premium: ₹15,000/year." },
      { step: "Never miss a renewal", description: "Upcoming renewals show up in your Reminders automatically.", example: "A reminder appears 30 days before your health policy expires." },
      { step: "Track tax deductions", description: "Premium amounts are used in the Tax module for 80C/80D calculations." },
    ],
    relatedFeatures: [
      { name: "Reminders", description: "Policy renewal dates auto-create reminders." },
      { name: "Tax", description: "Premiums are deductible under Section 80C and 80D." },
    ],
  },
  "/loans": {
    title: "Loans",
    summary: "Track every loan — home, car, personal — and see how much you still owe.",
    details: "Loans tracks your borrowings: principal, interest rate, tenure, EMI, lender, and type. Summary cards show total outstanding, total monthly EMI, and number of active loans. Outstanding balances feed into Net Worth as liabilities. EMI due dates create reminders automatically.",
    controls: [
      { name: "Add Loan Button", description: "Opens the form to add a new loan.", location: "Top bar" },
      { name: "Type Selector", description: "Home, Car, Personal, Education, Business, Other.", location: "Add form" },
      { name: "Principal Input", description: "Total amount borrowed.", location: "Add form" },
      { name: "Interest Rate Input", description: "Annual interest rate percentage.", location: "Add form" },
      { name: "Tenure Input", description: "Loan repayment period in months or years.", location: "Add form" },
      { name: "EMI Input", description: "Monthly installment amount.", location: "Add form" },
      { name: "Lender Input", description: "Bank or financial institution.", location: "Add form" },
      { name: "Start Date Picker", description: "When the loan was taken.", location: "Add form" },
      { name: "Summary Cards", description: "Total outstanding, total EMI, active loans count.", location: "Top" },
      { name: "Paid EMIs Tracker", description: "Update how many EMIs you've paid.", location: "Per loan card" },
      { name: "Edit/Delete", description: "Tap to edit; delete removes the loan from net worth.", location: "Per row" },
    ],
    workflow: [
      { step: "Add a loan", description: "Tap Add Loan. Enter the amount borrowed, interest rate, tenure, EMI, lender, and start date.", example: "Home Loan: ₹30,00,000, 8.5%, 20 years, EMI ₹26,000, SBI, started Jan 2024." },
      { step: "Track repayments", description: "Update paid EMIs to track progress. See how much is left.", example: "120 of 240 EMIs paid (50% complete). Outstanding: ₹18,00,000." },
      { step: "View summary", description: "Summary cards show your total debt burden at a glance.", example: "Total Outstanding: ₹35,00,000 across 3 loans." },
    ],
    relatedFeatures: [
      { name: "Net Worth", description: "Outstanding loan balances are your liabilities." },
      { name: "Reminders", description: "EMI due dates create reminders automatically." },
      { name: "Tax", description: "Home loan interest is tax-deductible under Section 24(b)." },
    ],
  },
  "/assets": {
    title: "Assets",
    summary: "Track physical things you own — property, gold, vehicles — and see how their value changes.",
    details: "Assets are the physical things you own that have value. Each asset records purchase price, current value, and purchase date. The app shows gain or loss per asset. Assets are grouped by category. Together with investments, they make up the assets side of your Net Worth.",
    controls: [
      { name: "Add Asset Button", description: "Opens the form to add a new physical asset.", location: "Top bar" },
      { name: "Category Selector", description: "Property, Vehicle, Gold/Jewellery, Art, Electronics, Other.", location: "Add form" },
      { name: "Asset Name Input", description: "Descriptive name for the asset.", location: "Add form" },
      { name: "Purchase Price Input", description: "What you paid when you bought it.", location: "Add form" },
      { name: "Current Value Input", description: "Estimated current market value.", location: "Add form" },
      { name: "Purchase Date Picker", description: "When you acquired the asset.", location: "Add form" },
      { name: "Gain/Loss Badge", description: "Shows profit or loss since purchase.", location: "Per asset card" },
      { name: "Filter by Category", description: "Show only Property, Vehicles, etc.", location: "Top" },
      { name: "Edit/Delete", description: "Tap to edit; delete removes from net worth.", location: "Per row" },
    ],
    workflow: [
      { step: "Add an asset", description: "Tap Add Asset. Pick a category, enter purchase price, current value, and purchase date.", example: "Category: Vehicle, Name: Honda City 2022, Purchase: ₹12,00,000, Current: ₹9,00,000." },
      { step: "Track value changes", description: "Update the current value over time — the app shows your gain or loss.", example: "Gold purchased at ₹5,000/gm now valued at ₹7,200/gm → Gain: 44%." },
      { step: "See category totals", description: "Assets are grouped by category with subtotals for each." },
    ],
    relatedFeatures: [
      { name: "Net Worth", description: "Asset values add to your net worth." },
      { name: "Investments", description: "Assets and investments together make up what you own." },
    ],
  },
  "/insights": {
    title: "Insights",
    summary: "See patterns in your spending and income — trends, category breakdowns, and comparisons.",
    details: "Insights analyses your financial data to show you patterns: monthly trend charts, category breakdowns, and year-over-year comparisons. Use the AI chat to ask natural language questions about your finances. Switch between different time ranges and chart types.",
    controls: [
      { name: "Time Range Selector", description: "1M, 3M, 6M, 1Y, or Custom date range.", location: "Top bar" },
      { name: "Chart Type Toggle", description: "Switch between Line, Bar, Pie, or Area charts.", location: "Above chart" },
      { name: "Income vs Expense Chart", description: "Trend comparison of income and spending over time.", location: "Main area" },
      { name: "Category Breakdown Chart", description: "Pie or bar chart of expenses by category.", location: "Below trend" },
      { name: "Year-over-Year Comparison", description: "Compare this year's data to the previous year.", location: "Scroll down" },
      { name: "AI Chat Button", description: "Floating button to open an AI assistant chat.", location: "Bottom right" },
      { name: "AI Chat Input", description: "Text field to ask questions about your data in natural language.", location: "Chat panel" },
    ],
    workflow: [
      { step: "View monthly trends", description: "Line charts show how your income and expenses change over time.", example: "See that your spending spiked in December (holiday season)." },
      { step: "Analyse categories", description: "Pie charts break down spending by category.", example: "40% Food, 20% Transport, 15% Shopping, 25% Bills." },
      { step: "Compare year-over-year", description: "See how this year compares to the same period last year.", example: "Income up 12%, Expenses up 8% vs last year." },
      { step: "Ask the AI", description: "Use the floating chat to ask questions about your data.", example: "Ask 'How much did I spend on food last month?'." },
    ],
    relatedFeatures: [
      { name: "Dashboard", description: "Insights is a deeper dive into Dashboard numbers." },
      { name: "Reports", description: "Reports offers exportable versions of similar analysis." },
    ],
  },
  "/reports": {
    title: "Reports",
    summary: "Deep-dive reports on every aspect of your finances — exportable to Excel or PDF.",
    details: "Reports gives you detailed analysis across tabs: Overview, Income, Expenses, Investments, Goals, Recurrence, and Data. Each tab can be filtered by date range and category. Export any tab to XLSX or PDF for sharing or record-keeping.",
    controls: [
      { name: "Tab Selector", description: "Horizontal scrollable tabs: Overview, Income, Expenses, Investments, Goals, Recurrence, Data.", location: "Top" },
      { name: "Date Range Picker", description: "Select start and end dates for the report.", location: "Below tabs" },
      { name: "Category Filter", description: "Filter by specific categories within each report tab.", location: "Next to date picker" },
      { name: "Export XLSX Button", description: "Downloads the current tab as an Excel file.", location: "Top right" },
      { name: "Export PDF Button", description: "Generates a PDF of the current tab.", location: "Top right" },
      { name: "Summary Cards", description: "Key metrics relevant to the selected tab.", location: "Top of each tab" },
    ],
    workflow: [
      { step: "Pick your report", description: "Choose from Overview, Income, Expenses, Investments, Goals, Recurrence, or Data.", example: "Select the 'Expenses' tab to see detailed spending analysis." },
      { step: "Set date filters", description: "Use date range and category filters to focus on what matters.", example: "Set range to Q1 2026 and category to 'Food'." },
      { step: "Export", description: "Export any tab to Excel or PDF with one tap.", example: "Tap PDF to generate a report for your financial advisor." },
    ],
    relatedFeatures: [
      { name: "Dashboard", description: "Reports gives you the drill-down behind Dashboard numbers." },
      { name: "Expenses", description: "The Expenses tab shows detailed spending analysis." },
      { name: "Insights", description: "Insights offers interactive charts; Reports gives you exportable data." },
    ],
  },
  "/reminders": {
    title: "Reminders",
    summary: "One place for every upcoming financial event — bill due dates, EMI payments, renewals.",
    details: "Reminders collects everything time-sensitive across all modules: EMI payments, insurance renewals, subscription renewals, and custom reminders. Each has a priority level and can be marked as done. Sort by date or priority to see what needs attention first.",
    controls: [
      { name: "Add Reminder Button", description: "Creates a custom reminder for anything not covered by auto-reminders.", location: "Top bar" },
      { name: "Reminder List", description: "All reminders sorted by due date with priority indicators.", location: "Main area" },
      { name: "Priority Badge", description: "High (red), Medium (yellow), Low (green) labels.", location: "Per reminder" },
      { name: "Mark Done Button", description: "Checkbox or button to mark a reminder as completed.", location: "Per row" },
      { name: "Filter by Module", description: "Show only Loan, Insurance, Subscription, or Custom reminders.", location: "Top" },
      { name: "Sort Toggle", description: "Switch between Date or Priority sorting.", location: "Top" },
      { name: "Snooze Button", description: "Postpone a reminder by a day, week, or month.", location: "Per row" },
    ],
    workflow: [
      { step: "See what's coming", description: "Reminders are sorted by due date with priority indicators.", example: "A red badge on an EMI reminder due tomorrow." },
      { step: "Mark as done", description: "Tap the checkbox to mark a reminder as completed.", example: "Mark 'Insurance Renewal' done after paying the premium." },
      { step: "Snooze if needed", description: "Tap snooze to postpone a reminder to a later date.", example: "Snooze 'Electricity Bill' by 3 days." },
      { step: "Add custom reminders", description: "Use Add Reminder for one-off events.", example: "Reminder: 'File ITR' due 31-Jul-2026." },
    ],
    relatedFeatures: [
      { name: "Loans", description: "EMI due dates create reminders automatically." },
      { name: "Insurance", description: "Policy renewal dates create reminders automatically." },
      { name: "Subscriptions", description: "Subscription renewal dates create reminders automatically." },
    ],
  },
  "/auto-link": {
    title: "Auto-Link",
    summary: "Let the app connect the dots between your expenses and other parts of your finances.",
    details: "Auto-Link looks at your expenses and suggests connections. For example, a GPay rent payment matching your rental income source, an expense tagged Investment that should become an investment record, or insurance expenses linking to your policies. Accept, tweak, or dismiss each suggestion.",
    controls: [
      { name: "Suggestion Cards", description: "Each card shows the proposed link between an expense and a target module.", location: "Main list" },
      { name: "Accept Button", description: "Applies the suggestion and creates the link.", location: "Per card" },
      { name: "Tweak Button", description: "Opens the suggestion for manual adjustment before accepting.", location: "Per card" },
      { name: "Dismiss Button", description: "Rejects the suggestion and removes it from the list.", location: "Per card" },
      { name: "Mark All Read", description: "Dismiss all current suggestions at once.", location: "Top bar" },
      { name: "Filter by Type", description: "Show only Income, Investment, or Insurance suggestions.", location: "Top" },
    ],
    workflow: [
      { step: "Review suggestions", description: "Each card shows an expense and the proposed auto-link target.", example: "Expense 'Rent ₹25,000 to Landlord' → Link to Income Source 'Rental Income'." },
      { step: "Accept a suggestion", description: "Tap the tick icon to accept. The link is created automatically.", example: "Accept → the expense is now linked to your Rental Income source." },
      { step: "Tweak before accepting", description: "Tap Tweak to adjust the mapping before applying.", example: "Change the category or amount before linking." },
      { step: "Dismiss unwanted suggestions", description: "Tap the cross to dismiss a suggestion you don't need." },
    ],
    relatedFeatures: [
      { name: "Income Sources", description: "GPay receipts matching your income source get linked automatically." },
      { name: "Investments", description: "Expenses tagged 'Investment' suggest creating investment records." },
      { name: "Insurance", description: "Insurance premium expenses link to your policies." },
    ],
  },
  "/deals": {
    title: "Deals & Offers",
    summary: "Keep track of coupons, discounts, and special offers from stores you shop at.",
    details: "Record deals from merchants you frequently use — discount amounts, coupon codes, validity dates, and terms. When you add an expense, check if there's an active deal to apply. Helps you save money by remembering offers you might otherwise forget.",
    controls: [
      { name: "Add Deal Button", description: "Opens the form to add a new deal or offer.", location: "Top bar" },
      { name: "Merchant Input", description: "Name of the store or service offering the deal.", location: "Add form" },
      { name: "Discount Input", description: "Percentage or fixed amount off.", location: "Add form" },
      { name: "Coupon Code Input", description: "The code to apply at checkout.", location: "Add form" },
      { name: "Valid Until Picker", description: "Deal expiration date.", location: "Add form" },
      { name: "Terms Input", description: "Minimum spend, exclusions, or other conditions.", location: "Add form" },
      { name: "Filter by Merchant", description: "Show deals for a specific store.", location: "Top" },
      { name: "Active/Expired Filter", description: "Show only deals that are still valid.", location: "Top" },
      { name: "Edit/Delete", description: "Tap to edit; delete expired deals.", location: "Per row" },
    ],
    workflow: [
      { step: "Add a deal", description: "Tap Add Deal. Enter the merchant, discount, coupon code, and validity.", example: "Amazon: 10% off, Code: SAVE10, valid until 31-Dec-2026." },
      { step: "Use a deal", description: "When adding an expense, check for active deals from that merchant.", example: "Adding an Amazon expense? Apply the SAVE10 coupon." },
      { step: "Clean up expired deals", description: "Delete or archive deals that have expired to keep the list tidy." },
    ],
    relatedFeatures: [
      { name: "Expenses", description: "Deals can help reduce what you spend at specific merchants." },
    ],
  },
  "/health": {
    title: "Financial Health Score",
    summary: "Get a report card for your finances with personalised tips to improve.",
    details: "Your Financial Health Score rates you from 0–100 across six areas: Cash Flow, Investments, Insurance, Tax, Debt, and Goals. Each area has its own score and specific recommendations. The overall score is shown as a gauge. Personalised AI-powered tips help you improve weak areas.",
    controls: [
      { name: "Score Gauge", description: "Large circular gauge showing your overall 0–100 score.", location: "Top" },
      { name: "Score Breakdown", description: "Six area cards, each with an individual score and colour indicator.", location: "Below gauge" },
      { name: "Area Detail Card", description: "Expanded view of each area with recommendations.", location: "Per area" },
      { name: "AI Tips Section", description: "Personalised suggestions generated by AI to improve your score.", location: "Bottom" },
      { name: "Refresh Button", description: "Recalculates the health score based on latest data.", location: "Top bar" },
    ],
    workflow: [
      { step: "Check your score", description: "The gauge shows your overall score from 0–100.", example: "Score: 72 — Good, but room for improvement." },
      { step: "See each area", description: "Each of the six areas has its own score and detailed breakdown.", example: "Investments: 65, Insurance: 80, Debt: 55, etc." },
      { step: "Read recommendations", description: "Get personalised AI-powered tips to improve each area.", example: "Debt is low (55) — consider a balance transfer to reduce interest." },
    ],
    relatedFeatures: [
      { name: "Dashboard", description: "The health gauge on your Dashboard links here." },
      { name: "What-If Simulator", description: "See how changes would affect your score." },
      { name: "Risk Profile", description: "Your risk profile calibrates parts of the Health Score." },
    ],
  },
  "/risk-profile": {
    title: "Risk Profile",
    summary: "Answer 10 questions to find out your investor personality — conservative, moderate, or aggressive.",
    details: "This 10-question quiz determines your risk tolerance across five dimensions: financial capacity, investment knowledge, time horizon, loss tolerance, and income stability. Your result influences investment recommendations and calibrates your Financial Health Score.",
    controls: [
      { name: "Question Card", description: "Each question with a clear prompt and multiple choice answers.", location: "Main area" },
      { name: "Answer Options", description: "Radio buttons or selectable chips for each question (typically 4–5 options).", location: "Per question" },
      { name: "Progress Indicator", description: "Shows question 3 of 10 or a progress bar.", location: "Top" },
      { name: "Previous/Next Buttons", description: "Navigate between questions.", location: "Bottom" },
      { name: "Submit Button", description: "Appears on the last question to calculate your result.", location: "Bottom" },
      { name: "Result Card", description: "Shows your profile: Conservative, Moderate, or Aggressive with description.", location: "After submission" },
    ],
    workflow: [
      { step: "Start the quiz", description: "Tap 'Start Assessment' to begin the 10-question risk profile quiz." },
      { step: "Answer each question", description: "Read each question and select the answer that best describes you.", example: "Q: 'How would you react to a 20% market drop?' → A: 'Hold and wait for recovery.'" },
      { step: "Submit your answers", description: "After question 10, tap Submit to see your risk profile.", example: "Result: Moderate Risk Profile — balanced approach to investing." },
      { step: "Re-take if needed", description: "Your risk profile can change over time. Re-take the quiz anytime." },
    ],
    relatedFeatures: [
      { name: "Financial Health", description: "Your risk profile calibrates the Health Score." },
      { name: "Investments", description: "Investment recommendations consider your risk profile." },
    ],
  },
  "/what-if": {
    title: "What-If Simulator",
    summary: "Play with your finances — see what happens if you save more, spend less, or invest differently.",
    details: "Tweak any financial parameter and see the projected impact on your Net Worth, savings rate, and goal timelines. Create multiple scenarios (e.g. 'Optimistic', 'Conservative') and compare them side by side. All scenarios are saved for future reference.",
    controls: [
      { name: "New Scenario Button", description: "Creates a new blank scenario to configure.", location: "Top bar" },
      { name: "Scenario Name Input", description: "Give your scenario a descriptive label.", location: "Scenario form" },
      { name: "Income Slider/Input", description: "Adjust expected income changes (%).", location: "Parameters section" },
      { name: "Expense Slider/Input", description: "Adjust expected expense changes (%).", location: "Parameters section" },
      { name: "Investment Return Slider", description: "Set expected annual return rate (%).", location: "Parameters section" },
      { name: "Loan Interest Slider", description: "Adjust loan interest rate assumptions.", location: "Parameters section" },
      { name: "Run Simulation Button", description: "Calculates the projected outcomes for this scenario.", location: "Bottom" },
      { name: "Results Chart", description: "Projected Net Worth and goal timeline charts.", location: "After running" },
      { name: "Scenario Comparison View", description: "Side-by-side comparison of multiple scenarios.", location: "Tab or toggle" },
      { name: "Delete Scenario", description: "Remove a saved scenario.", location: "Per scenario" },
    ],
    workflow: [
      { step: "Create a scenario", description: "Tap New Scenario. Give it a name.", example: "Scenario: 'Save More — 20% SIP increase'." },
      { step: "Adjust the numbers", description: "Change income, expenses, investment returns, or loan payments using sliders or inputs.", example: "Increase SIP by ₹10,000/month, reduce dining out by ₹3,000/month." },
      { step: "Run the simulation", description: "Tap Run Simulation to see the projected impact.", example: "Net Worth in 5 years: ₹1.2Cr (vs ₹95L baseline)." },
      { step: "Compare scenarios", description: "Create multiple scenarios and switch to Compare view to see them side by side.", example: "Compare 'Aggressive Saving' vs 'Conservative' vs 'Current Path'." },
    ],
    relatedFeatures: [
      { name: "Financial Health", description: "See how scenario changes affect your Health Score." },
      { name: "Goals", description: "Model how increased savings accelerate goal achievement." },
      { name: "Net Worth", description: "All scenarios project your future net worth." },
    ],
  },
  "/tax": {
    title: "Tax",
    summary: "Everything tax — calculate what you owe, store documents, track filings, and plan ahead.",
    details: "The Tax section has tabs for Income & Deductions, Documents, ITR Filings, and Projections. It auto-calculates your Gross Total Income from all income sources. Add deductions under various sections (80C, 80D, 24(b), etc.) and compare Old vs New tax regime side by side.",
    controls: [
      { name: "Tab Selector", description: "Tabs: Income & Deductions, Documents, ITR Filings, Projections.", location: "Top" },
      { name: "Gross Total Income Display", description: "Auto-calculated total from all income sources.", location: "Income tab" },
      { name: "Deduction Inputs", description: "Fields for 80C, 80D, 24(b), HRA, LTA, etc.", location: "Income tab" },
      { name: "Old vs New Comparison", description: "Side-by-side tax calculation for both regimes.", location: "Income tab" },
      { name: "Upload Document Button", description: "Upload Form 16, 26AS, receipts, and proofs.", location: "Documents tab" },
      { name: "Document Viewer", description: "View uploaded documents inline.", location: "Documents tab" },
      { name: "ITR Filing Form", description: "Record filing status, acknowledgment number, date, and refund amount.", location: "ITR Filings tab" },
      { name: "Projection Charts", description: "Estimated tax liability for current and future years.", location: "Projections tab" },
    ],
    workflow: [
      { step: "Review income & deductions", description: "Auto-calculates your income from all sources. Add deductions you're eligible for.", example: "Add 80C: ₹1,50,000 (PPF + ELSS), 80D: ₹25,000 (Health Insurance)." },
      { step: "Compare Old vs New regime", description: "See both tax calculations side by side to pick the better option.", example: "Old regime: ₹45,000 tax. New regime: ₹52,000 tax. Choose Old." },
      { step: "Upload documents", description: "Upload Form 16, 26AS, and other proofs for record-keeping.", example: "Upload Form 16 from your employer." },
      { step: "Track ITR filings", description: "Record your filing status, acknowledgment number, and expected refund.", example: "ITR filed on 15-Jul-2026, Ack: 123456, Refund: ₹8,000." },
    ],
    relatedFeatures: [
      { name: "Income Sources", description: "Your Gross Total Income comes from all income sources." },
      { name: "Investments", description: "Capital gains feed into tax calculations." },
      { name: "Insurance", description: "Premiums are deductible under 80C/80D." },
      { name: "Loans", description: "Home loan interest is deductible under Section 24(b)." },
    ],
  },
  "/plans": {
    title: "Plans & Pricing",
    summary: "See what each subscription tier offers and upgrade when you're ready.",
    details: "MyMoney offers Free (₹0), Pro (₹99/month or ₹999/year), and Enterprise (custom) tiers. Each tier lists its included features. Upgrade via Razorpay — payment is instant and your account upgrades automatically. The Enterprise tier includes custom onboarding, dedicated support, and white-label options.",
    controls: [
      { name: "Tier Cards", description: "Three cards showing Free, Pro, and Enterprise features.", location: "Main area" },
      { name: "Current Plan Badge", description: "Label showing which tier you're currently on.", location: "Per card" },
      { name: "Upgrade Button", description: "Opens Razorpay checkout to upgrade your plan.", location: "Pro and Enterprise cards" },
      { name: "Monthly/Yearly Toggle", description: "Switch between monthly and yearly pricing for Pro.", location: "Pro card" },
      { name: "Feature Comparison Table", description: "Detailed comparison of features across all tiers.", location: "Below cards" },
    ],
    workflow: [
      { step: "Review the tiers", description: "Compare features across Free, Pro, and Enterprise.", example: "Pro adds: Reports, Auto-Link, Gmail Import, and multi-device sync." },
      { step: "Choose your plan", description: "Select monthly or yearly billing for Pro.", example: "Pro Yearly: ₹999/year (saves ₹189 vs monthly)." },
      { step: "Upgrade", description: "Tap Upgrade and complete payment via Razorpay. Your account upgrades instantly." },
    ],
    relatedFeatures: [
      { name: "Feature Flags", description: "Your tier determines which features are available." },
      { name: "Settings", description: "Manage your subscription and billing from Settings." },
    ],
  },
  "/family": {
    title: "Family Sharing",
    summary: "Share finances with family members — let them view or edit with your permission.",
    details: "Invite family members to access your financial data. You control whether each member can view only, add/edit, or have full admin access. All invited members see a shared view of the same data. Great for household finances where both partners need to track expenses together.",
    controls: [
      { name: "Invite Member Button", description: "Sends an invitation to a family member via email.", location: "Top bar" },
      { name: "Email Input", description: "Enter the email address of the person you want to invite.", location: "Invite form" },
      { name: "Permission Selector", description: "Choose: View Only, Add/Edit, or Admin.", location: "Invite form" },
      { name: "Member List", description: "All current family members with their permission levels.", location: "Main area" },
      { name: "Edit Permission", description: "Change a member's access level.", location: "Per member" },
      { name: "Remove Member", description: "Revoke access for a family member.", location: "Per member" },
      { name: "Pending Invites", description: "List of invitations that haven't been accepted yet.", location: "Below member list" },
    ],
    workflow: [
      { step: "Invite a family member", description: "Tap Invite Member, enter their email, and choose their permission level.", example: "Invite spouse: Add/Edit permission." },
      { step: "Manage permissions", description: "Edit a member's access level at any time.", example: "Change a member from 'View Only' to 'Add/Edit' during vacation." },
      { step: "Remove access", description: "Remove a member when they no longer need access.", example: "Remove a sibling after settling joint expenses." },
    ],
    relatedFeatures: [
      { name: "Settings", description: "Family sharing settings are managed from this page." },
    ],
  },
  "/gmail-import": {
    title: "Gmail Import",
    summary: "Scan your email inbox to automatically pull in financial transactions.",
    details: "Connect your Gmail (read-only access) and the app scans for financial emails. It recognises UPI receipts, bank alerts, salary credits, mutual fund transactions, insurance premiums, and tax documents. You review and pick which ones to import as expenses, income, or investments.",
    controls: [
      { name: "Connect Gmail Button", description: "Initiates OAuth to grant read-only Gmail access.", location: "Top" },
      { name: "Scan Button", description: "Triggers a scan of your inbox for financial emails.", location: "Top bar" },
      { name: "Date Range Selector", description: "Define the email date range to scan.", location: "Scan settings" },
      { name: "Email List", description: "Identified financial emails with type labels (UPI, Bank Alert, Salary, etc.).", location: "Main area" },
      { name: "Import Toggle", description: "Checkbox per email to select which ones to import.", location: "Per email" },
      { name: "Import Selected Button", description: "Imports all checked emails into the respective modules.", location: "Bottom" },
      { name: "Select All Toggle", description: "Check/uncheck all identified emails at once.", location: "Top bar" },
      { name: "Disconnect Gmail", description: "Revoke Gmail access at any time.", location: "Settings within page" },
    ],
    workflow: [
      { step: "Connect your Gmail", description: "Tap Connect Gmail and grant read-only access via OAuth. The app never sees your full inbox.", example: "Sign in with your Gmail account and allow access." },
      { step: "Scan for transactions", description: "Tap Scan. The app searches your inbox for financial emails.", example: "Found 23 emails: 12 UPI receipts, 5 bank alerts, 3 salary credits, 2 MF transactions, 1 tax document." },
      { step: "Select what to import", description: "Toggle the emails you want to import. You can select all or pick individually." },
      { step: "Import", description: "Tap Import Selected. Each email creates an expense, income source, or investment record.", example: "12 UPI receipts → 12 new expenses. Salary credit → new income source." },
    ],
    relatedFeatures: [
      { name: "Expenses", description: "UPI payments and debit alerts become expenses." },
      { name: "Income Sources", description: "Salary credit emails create monthly income records." },
      { name: "Investments", description: "Mutual fund and stock emails create investment records." },
      { name: "Settings", description: "Configure Gmail keywords and parsing rules in Settings." },
    ],
  },
  "/settings": {
    title: "Settings",
    summary: "Manage your account, connect integrations, and configure how the app works.",
    details: "Settings is the hub for all configuration. Sections include Account Profile, Session Link, API Keys, Gmail Parser, Broker Integrations, Bank Accounts, Environment Configuration, and App Preferences. Each section opens its own sub-page with detailed controls.",
    controls: [
      { name: "Settings Menu List", description: "Navigation list with all settings sections.", location: "Main area" },
      { name: "Profile Section", description: "Your name, email, avatar, and account preferences.", location: "Menu item" },
      { name: "Toggle Switches", description: "On/off toggles for various app preferences like notifications, dark mode, etc.", location: "Per preference" },
      { name: "Chevron Navigation", description: "Tap any settings row to navigate to its sub-page.", location: "Per menu item" },
      { name: "Logout Button", description: "Signs you out of your account.", location: "Bottom of menu" },
    ],
    workflow: [
      { step: "Navigate settings", description: "Scroll through the menu and tap any section to open its configuration page.", example: "Tap 'Gmail Parser' to configure email keywords." },
      { step: "Toggle preferences", description: "Use switches to enable or disable features like notifications.", example: "Toggle 'Push Notifications' on for due date alerts." },
      { step: "Logout", description: "Scroll to the bottom and tap Logout to sign out of your account." },
    ],
    relatedFeatures: [
      { name: "API Keys", description: "Generate and manage API keys for external access." },
      { name: "Gmail Import", description: "Configure how Gmail imports work." },
      { name: "Bank Accounts", description: "Manage account links that feed into Net Worth." },
      { name: "Integrations", description: "Connect broker accounts for automatic portfolio sync." },
    ],
  },
  "/settings/api-keys": {
    title: "API Keys",
    summary: "Generate and manage API keys for programmatic access to your data.",
    details: "API keys allow external applications to read your financial data. Each key has a name, generated token, last used timestamp, and permissions scope. You can create new keys, copy the token, or revoke a key if it's compromised or no longer needed.",
    controls: [
      { name: "Create API Key Button", description: "Opens a form to generate a new API key.", location: "Top bar" },
      { name: "Key Name Input", description: "A label to identify what this key is used for.", location: "Create form" },
      { name: "Permission Selector", description: "Read-only or Read/Write scope.", location: "Create form" },
      { name: "Key Display", description: "The generated token shown once after creation (with copy button).", location: "After creation" },
      { name: "Copy Button", description: "Copies the API key to clipboard.", location: "Per key" },
      { name: "Revoke Button", description: "Permanently invalidates an API key with confirmation.", location: "Per key" },
      { name: "Key List", description: "All active keys with name, last used, and creation date.", location: "Main area" },
      { name: "Last Used Timestamp", description: "Shows when each key was last accessed.", location: "Per key" },
    ],
    workflow: [
      { step: "Create a new key", description: "Tap Create API Key. Give it a name and choose the permission scope.", example: "Name: 'Budget App Integration', Scope: Read-only." },
      { step: "Copy your key", description: "The key is shown once. Tap Copy and store it securely.", example: "Key: mk_abc123... (copy to clipboard)." },
      { step: "Revoke a key", description: "If a key is compromised or unused, tap Revoke to invalidate it.", example: "Revoke a key you shared with a developer who no longer needs access." },
    ],
    relatedFeatures: [
      { name: "Settings", description: "API Keys is a sub-section of the main Settings page." },
      { name: "Integrations", description: "API keys are used by third-party integrations." },
    ],
  },
  "/settings/bank-accounts": {
    title: "Bank Account Settings",
    summary: "Manage linked bank accounts and configure sync settings.",
    details: "Configure all your linked bank accounts from one place. Add new accounts, edit existing ones, update balances, or remove accounts. This page mirrors the main Bank Accounts page but is nested within Settings for easy access during configuration.",
    controls: [
      { name: "Add Account Button", description: "Opens the form to add a new bank account.", location: "Top bar" },
      { name: "Account List", description: "All linked accounts with name, type, and balance.", location: "Main area" },
      { name: "Edit Account", description: "Modify bank name, account number, IFSC, or type.", location: "Per row" },
      { name: "Update Balance", description: "Inline edit to set the current balance.", location: "Per row" },
      { name: "Remove Account", description: "Delete an account with confirmation.", location: "Per row" },
      { name: "Auto-Sync Toggle", description: "Enable/disable automatic balance updates if available.", location: "Per row" },
    ],
    workflow: [
      { step: "Add a new account", description: "Tap Add Account and enter bank details.", example: "ICICI Bank, Savings, Balance: ₹75,000." },
      { step: "Update balances", description: "Tap the balance field to enter the latest amount.", example: "Update savings balance to ₹78,500." },
      { step: "Remove an account", description: "Tap Remove and confirm to delete the account from your profile." },
    ],
    relatedFeatures: [
      { name: "Bank Accounts", description: "This is the settings version of the main Bank Accounts page." },
      { name: "Net Worth", description: "Account balances feed directly into your net worth calculation." },
    ],
  },
  "/settings/environment": {
    title: "Environment Configuration",
    summary: "Switch between development, staging, and production API environments.",
    details: "For advanced users and developers. Toggle between API environments to test against different backends. Changes take effect on the next API call. The current environment is clearly displayed with a colour badge.",
    controls: [
      { name: "Environment Selector", description: "Radio buttons or segmented control: Development, Staging, Production.", location: "Main area" },
      { name: "Current Environment Badge", description: "Colour-coded badge showing which environment is active.", location: "Top" },
      { name: "API URL Display", description: "The base URL for the selected environment.", location: "Below selector" },
      { name: "Save Button", description: "Applies the environment change.", location: "Bottom" },
      { name: "Reset to Production", description: "One-tap button to switch back to production.", location: "Bottom" },
    ],
    workflow: [
      { step: "Select an environment", description: "Tap Development, Staging, or Production.", example: "Select 'Staging' to test against the staging server." },
      { step: "Verify the URL", description: "Check the displayed API URL to confirm it's correct.", example: "https://api-staging.mymoney.app/v1." },
      { step: "Save", description: "Tap Save to apply. The change takes effect immediately." },
    ],
    relatedFeatures: [
      { name: "Settings", description: "Environment config is a sub-section of Settings." },
      { name: "API Keys", description: "Some API keys may be environment-specific." },
    ],
  },
  "/settings/gmail-parser": {
    title: "Gmail Parser Keywords",
    summary: "Configure which email keywords trigger financial transaction detection.",
    details: "Manage the rules that the Gmail Import feature uses to identify financial emails. Each rule has a keyword, the transaction type it represents (expense, income, investment), and whether it's active. Add your own keywords for email patterns the app should recognise.",
    controls: [
      { name: "Add Keyword Button", description: "Opens a form to add a new parsing rule.", location: "Top bar" },
      { name: "Keyword Input", description: "Word or phrase to match in email subject or body.", location: "Add form" },
      { name: "Transaction Type Selector", description: "Expense, Income, Investment, Insurance, Tax, or Other.", location: "Add form" },
      { name: "Active Toggle", description: "Enable or disable this keyword rule.", location: "Per rule" },
      { name: "Rule List", description: "All configured keywords with their type and active status.", location: "Main area" },
      { name: "Default Rules Indicator", description: "Shows which rules are built-in vs user-created.", location: "Per rule" },
      { name: "Edit/Delete", description: "Modify or remove a custom rule.", location: "Per rule" },
    ],
    workflow: [
      { step: "Add a keyword", description: "Tap Add Keyword. Enter the word/phrase and select the transaction type.", example: "Keyword: 'UPI Credit', Type: Income." },
      { step: "Toggle rules on/off", description: "Use the toggle to temporarily disable a rule without deleting it.", example: "Disable 'Amazon' keyword during a shopping-heavy month." },
      { step: "Delete custom rules", description: "Remove user-added rules that are no longer needed. Default rules cannot be deleted." },
    ],
    relatedFeatures: [
      { name: "Gmail Import", description: "These keywords power the Gmail Import scanning engine." },
      { name: "Settings", description: "Gmail Parser is a sub-section of Settings." },
    ],
  },
  "/settings/integrations": {
    title: "Integrations",
    summary: "Connect external services — brokers, banks, and APIs — to auto-sync your data.",
    details: "Integrations lets you connect third-party services. Broker integrations (Zerodha, Groww, etc.) auto-sync your investment portfolio. You can also configure webhooks for real-time data updates. Each integration shows its connection status and last sync time.",
    controls: [
      { name: "Integration List", description: "All available integrations with connection status (Connected/Disconnected).", location: "Main area" },
      { name: "Connect Button", description: "Initiates OAuth or credential flow to link a service.", location: "Per integration" },
      { name: "Disconnect Button", description: "Revokes access to a connected integration.", location: "Per integration" },
      { name: "Sync Now Button", description: "Triggers an immediate data sync for a connected integration.", location: "Per integration" },
      { name: "Last Sync Timestamp", description: "Shows when data was last synced.", location: "Per integration" },
      { name: "Webhook URL Display", description: "Shows the webhook URL for real-time data pushes.", location: "Per integration (if applicable)" },
    ],
    workflow: [
      { step: "Connect an integration", description: "Tap Connect on your chosen service. Follow the OAuth or credential flow.", example: "Tap 'Zerodha' → log in to Zerodha → Authorize → Connected." },
      { step: "Sync your data", description: "After connecting, tap Sync Now to pull in your portfolio.", example: "Sync → 15 stocks and 5 mutual funds imported." },
      { step: "Disconnect when done", description: "Tap Disconnect and confirm to revoke access.", example: "Disconnect a broker you no longer use." },
    ],
    relatedFeatures: [
      { name: "Investments", description: "Broker integrations auto-populate your investment portfolio." },
      { name: "Settings", description: "Integrations is a sub-section of Settings." },
      { name: "API Keys", description: "Some integrations may use API keys instead of OAuth." },
    ],
  },
  "/settings/session-link": {
    title: "Session Link",
    summary: "Share a temporary link to let someone view your finances without creating an account.",
    details: "Session Link generates a temporary, shareable URL that lets anyone view your financial data without signing up. Set an expiration time and choose what data is visible. Revoke the link at any time. Useful for sharing with a financial advisor or family member temporarily.",
    controls: [
      { name: "Generate Link Button", description: "Creates a new session link.", location: "Top" },
      { name: "Expiration Selector", description: "1 hour, 24 hours, 7 days, or Custom.", location: "Generate form" },
      { name: "Permission Selector", description: "Choose which modules are visible via the link.", location: "Generate form" },
      { name: "Generated Link Display", description: "The full URL that can be copied and shared.", location: "After generation" },
      { name: "Copy Link Button", description: "Copies the session link to clipboard.", location: "Per link" },
      { name: "Revoke Button", description: "Invalidates a session link immediately.", location: "Per link" },
      { name: "Active Links List", description: "All currently active session links with expiry.", location: "Below" },
    ],
    workflow: [
      { step: "Generate a link", description: "Tap Generate Link. Set an expiration time and choose what to share.", example: "Expires in 24 hours, share: Net Worth + Investments only." },
      { step: "Share the link", description: "Tap Copy and send it via WhatsApp, email, or any messaging app.", example: "Send the link to your financial advisor for a review." },
      { step: "Revoke when done", description: "After the review, tap Revoke to invalidate the link.", example: "Revoke once the advisor has finished their analysis." },
    ],
    relatedFeatures: [
      { name: "Settings", description: "Session Link is a sub-section of Settings." },
      { name: "Family", description: "Session Link is a temporary alternative to permanent Family Sharing." },
    ],
  },
  "/login": {
    title: "Login",
    summary: "Sign in to your MyMoney account to access your financial data.",
    details: "Login securely with your email and password, or use Google OAuth for one-tap access. Your session is encrypted and persisted. If you forget your password, use the Forgot Password link to reset it. New users can navigate to the Sign Up option.",
    controls: [
      { name: "Email Input", description: "Text field for your registered email address.", location: "Form" },
      { name: "Password Input", description: "Secure text field for your password (with show/hide toggle).", location: "Form" },
      { name: "Login Button", description: "Submit credentials and authenticate.", location: "Form bottom" },
      { name: "Google OAuth Button", description: "One-tap sign-in with your Google account.", location: "Below form" },
      { name: "Forgot Password Link", description: "Opens a password reset flow via email.", location: "Below password field" },
      { name: "Sign Up Link", description: "Navigates to the registration screen for new users.", location: "Bottom" },
      { name: "Show/Hide Password Toggle", description: "Eye icon to toggle password visibility.", location: "Password field" },
    ],
    workflow: [
      { step: "Enter your credentials", description: "Type your registered email and password.", example: "Email: user@example.com, Password: ••••••••." },
      { step: "Sign in", description: "Tap Login. If credentials are correct, you're taken to the Dashboard.", example: "Successful login → Dashboard loads with your data." },
      { step: "Use Google OAuth", description: "Tap 'Sign in with Google' and select your account for one-tap access." },
      { step: "Reset password", description: "If you forgot your password, tap 'Forgot Password?' and follow the email instructions.", example: "Enter email → check inbox → click reset link → set new password." },
    ],
    relatedFeatures: [
      { name: "Onboarding", description: "New users start with the onboarding wizard after sign up." },
      { name: "Settings", description: "Manage your account profile and preferences after login." },
    ],
  },
  "/guide": {
    title: "Guide",
    summary: "Interactive walkthrough of all major features in the MyMoney app.",
    details: "The Guide provides a step-by-step tour of every major module. Each step explains what the feature does and how to use it. Mark steps as complete as you go through them. You can jump to any section or restart the guide at any time.",
    controls: [
      { name: "Step List", description: "Numbered list of all guide sections with completion status.", location: "Main area" },
      { name: "Step Content Card", description: "Detailed explanation and instructions for the current step.", location: "Below list" },
      { name: "Mark Complete Button", description: "Checkbox or button to mark the current step as done.", location: "Per step" },
      { name: "Next/Previous Navigation", description: "Buttons to move between guide steps.", location: "Bottom" },
      { name: "Jump to Step", description: "Tap any step in the list to navigate directly to it.", location: "Step list" },
      { name: "Reset Progress", description: "Clears all completion marks and restarts the guide.", location: "Top bar" },
      { name: "Progress Bar", description: "Shows overall completion percentage of the guide.", location: "Top" },
    ],
    workflow: [
      { step: "Start the guide", description: "The guide opens to step 1. Read the explanation for each feature." },
      { step: "Try the feature", description: "After reading, navigate to the feature and try it. Return to the guide to mark it complete.", example: "Read about Expenses → go add an expense → mark complete." },
      { step: "Track your progress", description: "The progress bar and step list show how far you've come.", example: "8 of 15 steps completed (53%)." },
      { step: "Jump ahead or restart", description: "Use the step list to jump to any section. Reset clears all progress.", example: "Skip to 'Reports' if that's what you need help with." },
    ],
    relatedFeatures: [
      { name: "Onboarding", description: "The Guide complements the initial Onboarding wizard." },
      { name: "All Features", description: "The Guide covers every major feature in the app." },
    ],
  },
  "/privacy": {
    title: "Privacy Policy",
    summary: "How MyMoney handles your data — we take your privacy seriously.",
    details: "Your financial data is encrypted at rest and in transit. MyMoney never shares your data with third parties. Read the full policy for details on data collection, storage, encryption, retention, and your rights under applicable privacy laws.",
    controls: [
      { name: "Policy Content", description: "Full privacy policy document in a scrollable view.", location: "Main area" },
      { name: "Last Updated Date", description: "Shows when the policy was last updated.", location: "Top" },
    ],
    workflow: [
      { step: "Read the policy", description: "Scroll through the full privacy policy document." },
      { step: "Check the update date", description: "The last updated date at the top tells you when it was last revised." },
    ],
    relatedFeatures: [],
  },
  "/onboarding": {
    title: "Onboarding Wizard",
    summary: "Set up your profile in minutes — add your first income, expenses, and preferences.",
    details: "The Onboarding wizard guides new users through initial setup. Steps include: creating your profile, adding your first income source, recording an expense, setting a budget, linking a bank account, and configuring preferences. Each step has a clear explanation and input fields.",
    controls: [
      { name: "Step Indicator", description: "Dots or numbers showing current step out of total (e.g. 3 of 6).", location: "Top" },
      { name: "Step Content", description: "Form fields and explanations for the current onboarding step.", location: "Main area" },
      { name: "Next Button", description: "Proceed to the next onboarding step.", location: "Bottom right" },
      { name: "Back Button", description: "Go back to the previous step.", location: "Bottom left" },
      { name: "Skip Button", description: "Skip this step and move to the next one.", location: "Top right" },
      { name: "Finish Button", description: "Appears on the last step to complete onboarding.", location: "Bottom right" },
      { name: "Progress Bar", description: "Visual bar showing overall progress through the wizard.", location: "Top" },
    ],
    workflow: [
      { step: "Create your profile", description: "Enter your name, email, and set your currency (₹)." },
      { step: "Add your first income", description: "Enter your primary income source, e.g. Salary: ₹75,000/month.", example: "Salary, ₹75,000, Monthly." },
      { step: "Record an expense", description: "Add a recent expense to see how tracking works.", example: "Food, ₹450, UPI, today." },
      { step: "Set a budget", description: "Create your first budget to start tracking spending.", example: "Food: ₹10,000/month." },
      { step: "Link a bank account", description: "Add your primary bank account to track net worth.", example: "HDFC Savings, balance: ₹50,000." },
      { step: "Configure preferences", description: "Set notification preferences, theme, and privacy options. Tap Finish to start using the app." },
    ],
    relatedFeatures: [
      { name: "Guide", description: "After onboarding, use the Guide for detailed feature walkthroughs." },
      { name: "Dashboard", description: "After onboarding, you land on the Dashboard." },
    ],
  },
  "/admin/features": {
    title: "Admin — Feature Flags",
    summary: "Toggle feature availability per subscription tier across the app.",
    details: "Feature flags let admins control which features are available for each tier (Free, Pro, Enterprise). Each flag has a key name, description, and can be enabled/disabled per tier. Changes take effect immediately without a deploy. Use this to roll out features gradually or A/B test.",
    controls: [
      { name: "Feature Flag List", description: "All feature flags with their keys, descriptions, and per-tier toggles.", location: "Main area" },
      { name: "Tier Toggle Switches", description: "Enable/disable a feature for Free, Pro, or Enterprise tiers.", location: "Per flag row" },
      { name: "Search/Filter Flags", description: "Search by flag key or name to find specific flags quickly.", location: "Top" },
      { name: "Add Flag Button", description: "Creates a new feature flag with key, description, and default values.", location: "Top bar" },
      { name: "Edit Flag", description: "Modify a flag's key, description, or tier enablement.", location: "Per flag" },
      { name: "Delete Flag", description: "Remove a feature flag permanently.", location: "Per flag" },
    ],
    workflow: [
      { step: "Find a flag", description: "Browse or search the list of all feature flags.", example: "Search 'gmail' to find gmail-import flag." },
      { step: "Toggle for a tier", description: "Switch the toggle on/off for Free, Pro, or Enterprise.", example: "Enable 'gmail-import' for Pro and Enterprise only." },
      { step: "Add a new flag", description: "Tap Add Flag. Enter a key name, description, and set initial tier values.", example: "Key: 'new-reports', Description: 'New report engine', Pro & Enterprise: ON." },
    ],
    relatedFeatures: [
      { name: "Plans", description: "Feature flags define what each subscription tier can access." },
      { name: "Admin Users", description: "Manage which admin users can modify feature flags." },
    ],
  },
  "/admin/users": {
    title: "Admin — Users",
    summary: "Manage all user accounts — view, edit roles, and control access.",
    details: "Admin users can view all registered accounts, search by name or email, edit user profiles (name, email, role, tier), enable/disable accounts, and delete users. Role options include User, Admin, and Super Admin. Tier can be set to Free, Pro, or Enterprise.",
    controls: [
      { name: "User List", description: "All registered users with name, email, role, tier, and status.", location: "Main area" },
      { name: "Search Bar", description: "Search users by name, email, or user ID.", location: "Top" },
      { name: "Role Selector", description: "Dropdown per user to change between User, Admin, Super Admin.", location: "Per row" },
      { name: "Tier Selector", description: "Dropdown per user to set Free, Pro, or Enterprise tier.", location: "Per row" },
      { name: "Enable/Disable Toggle", description: "Activate or deactivate a user account.", location: "Per row" },
      { name: "Delete User", description: "Permanently delete a user account with confirmation.", location: "Per row menu" },
      { name: "Invite User Button", description: "Send an invitation email to create a new account.", location: "Top bar" },
      { name: "Export Users", description: "Download the user list as CSV.", location: "Top bar" },
    ],
    workflow: [
      { step: "Find a user", description: "Use the search bar to find a user by name or email.", example: "Search 'john@example.com'." },
      { step: "Edit a user", description: "Change their role, tier, or enable/disable their account.", example: "Change tier from Free to Pro for a new paying customer." },
      { step: "Delete a user", description: "Use the menu to permanently delete a user. This removes all their data.", example: "Delete a duplicate test account." },
      { step: "Invite a new user", description: "Tap Invite User, enter their email, and they'll receive a sign-up link." },
    ],
    relatedFeatures: [
      { name: "Admin Feature Flags", description: "Control which features users can access based on their tier." },
      { name: "Admin Audit Log", description: "All user changes are logged in the audit log." },
    ],
  },
  "/admin/audit-log": {
    title: "Admin — Audit Log",
    summary: "Full history of every admin action — who did what and when.",
    details: "The audit log records all administrative actions: user creation, role changes, tier changes, account enable/disable, feature flag toggles, and deletions. Each entry shows the admin who performed the action, the target user or resource, the action type, and a timestamp. Filter by action type or date range.",
    controls: [
      { name: "Log Entry List", description: "All audit entries with admin, action, target, and timestamp.", location: "Main area" },
      { name: "Filter by Action Type", description: "Dropdown to filter by: User Created, Role Changed, Tier Changed, Flag Toggled, Account Deleted, etc.", location: "Top" },
      { name: "Date Range Picker", description: "Filter entries between specific dates.", location: "Top" },
      { name: "Search", description: "Search by admin name, target email, or action description.", location: "Top" },
      { name: "Export Log", description: "Download the audit log as CSV or PDF.", location: "Top bar" },
      { name: "Refresh Button", description: "Fetch the latest audit entries.", location: "Top bar" },
    ],
    workflow: [
      { step: "Browse the log", description: "All actions are listed chronologically with newest first.", example: "See that 'admin@mymoney.app changed user@example.com to Pro tier'." },
      { step: "Filter by action", description: "Use the Action Type filter to narrow down specific changes.", example: "Filter 'Tier Changed' to see all recent plan upgrades." },
      { step: "Search for an entry", description: "Use the search bar to find actions by a specific admin or target.", example: "Search by an admin's email to see all changes they made." },
      { step: "Export for records", description: "Tap Export to download the log for compliance or record-keeping.", example: "Export last month's audit log for a compliance review." },
    ],
    relatedFeatures: [
      { name: "Admin Users", description: "All user management actions are recorded here." },
      { name: "Admin Feature Flags", description: "All feature flag changes are recorded here." },
    ],
  },
}

export function getHelpForPath(path: string): HelpSection | null {
  if (helpContent[path]) return helpContent[path]

  const parts = path.split("/").filter(Boolean)
  while (parts.length > 0) {
    parts.pop()
    const parent = "/" + parts.join("/")
    if (helpContent[parent]) return helpContent[parent]
  }

  return null
}
